[phases.setup]
nixPkgs = ['python311', 'pip', 'chromium', 'chromedriver']

[phases.install]
cmd = 'pip install -r requirements.txt'

[variables]
CHROME_BIN = '/nix/store/*/bin/chromium'
CHROMEDRIVER_PATH = '/nix/store/*/bin/chromedriver'

[start]
cmd = 'python simple_app.py'
